[features]
seeds = false
skip-lint = false
[programs.localnet]
soldice_anchor = "6a84EaQix213TCn5vPRZBPE6Zoc8hxJBN9ax1KJ55cdg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
